### PR TITLE
PG 16 support

### LINKED ISSUE #17: The 1.5 release fails to build on PG16
When trying to compile the 1.5 release with PG16 I get the following compiler error:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I/usr/pgsql-16/include -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -DGIT_HASH=\"1.5\"  -c -o pgnodemx.o pgnodemx.c
In file included from pgnodemx.c:60:
genutils.h:41:31: error: conflicting types for ‘find_option’
 extern struct config_generic *find_option(const char *name);

I was able to compile it fine for PG11 through PG15 on multiple different operating systems, but I get this same failure trying to compile with PG16 on every operating system.

### PR DESCRIPTION
**Pull request by keithf4**
Closes #17 

Looks like the functions complained about during 16 building are copies of functions that exist in core

`float8in_internal` (and its associated `float8in_internal_opt_error`) were only ever getting included in the build if the version of PG was less than 9.0. The new version in 16 adds an `ErrorSaveContext` node parameter to the end, but I think we can just pass NULL to this? Removed all the code in the 9.0 conditional and did a conditional around the one call for PG16's new format.

`find_option` prior to PG16 was defined in guc.c and only ever used there, so it had no header entries. PG16 added it to a header file that was already being included (`src/include/utils/guc_tables.h`) which caused the error. Added version conditionals around this function and related functions only used within it. So PG16+ uses upstream function while older versions use the custom one. Can phase that out once old versions aren't supported anymore

### CODE REVIEW

File: parseutils.c [hunk 1]
```diff
@@ -596,8 +406,11 @@ get_double_from_file(char *ftr)
 	if (strcmp(rawstr, "max") == 0)
 		result = DBL_MAX;
 	else
+        #if PG_VERSION_NUM < 160000
 		result = float8in_internal(rawstr, NULL, "double precision", rawstr);
-
+        #else
+		result = float8in_internal(rawstr, NULL, "double precision", rawstr, NULL);
```
Comment (cbandy) [inline parseutils.c:412]: This last `Node` argument is passed to `ereturn()` calls. I don't know this part of the system, so I don't know if `NULL` is safe to use here. I defer to @pgguru.

File: genutils.c [hunk 2]
```diff
@@ -62,8 +62,14 @@
 #include "parseutils.h"
 #include "srfsigs.h"
 
+#if PG_VERSION_NUM < 160000
+/* These two functions are used via custom find_option() function
+    Once custom find_option is dropped in PG16+, remove these
+    unused functions here and full definitions below
+    https://github.com/CrunchyData/pgnodemx/pull/18 */
```
Comment (cbandy) [inline genutils.c:69]: 🤔 In other extension work I've done, the compiler warns about unused functions. I wonder if comments like these are necessary if we listen to warnings.

🤔 I'm also used to `#if PG_VERSION_NUM` and recognize that it means we can drop this code once PG 15 is gone.

I like clarity, so no blockers here!

**Review by cbandy — APPROVED** [review]
Macros look good to me. My one concern is that NULL Node pointer.

File: parseutils.c (hunk 1 above)
Comment (pgguru) [reply parseutils.c:412]: Looks like if it's `NULL` then it just throws a normal error; the context is used for soft erroring, so won't abort but captures info about the exception.  I'd say this current usage is fine, since the previous version wouldn't be using soft error support.

Comment (pgguru) [reply parseutils.c:412]: (see what eventually becomes `errsave_start()` via `errsave_domain()` and `ereport()`)

File: genutils.c (hunk 2 above)
Comment (pgguru) [reply genutils.c:69]: Agreed that to me the `#ifdef` is sufficient to illustrate intent, but the extra comment doesn't bother me too much.

Comment (keithf4) [reply genutils.c:69]: Yeah I didn't put the note on the find_option function itself, but figured it might be useful to speed up code review when removing later if it's explicitly noted these aren't used anywhere else.

File: parseutils.c (hunk 1 above)
Comment (keithf4) [reply parseutils.c:412]: Assuming you're ok with that response @cbandy, feel free to resolve this

Comment (cbandy) [reply parseutils.c:412]: I can't resolve, but sounds good to me! 👍🏻
